ReadLater5/ReadLater5/Controllers/BookmarksController.cs
using Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReadLater5.Models;
using Services;
using System.Collections.Generic;
using System.Linq;

namespace ReadLater5.Controllers
{
    [Authorize]
    public class BookmarksController : Controller
    {
        private readonly IBookmarkService _bookmarkService;
        private readonly ICategoryService _categoryService;

        public BookmarksController(IBookmarkService bookmarkService, ICategoryService categoryService)
        {
            _bookmarkService = bookmarkService;
            _categoryService = categoryService;
        }

        [Authorize]
        public IActionResult Index()
        {
            var model = _bookmarkService.GetBookmarks();
            return View(model);
        }

        [Authorize]
        public IActionResult Details(int? id)
        {
            if (id == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            
            Bookmark bookmark = _bookmarkService.GetBookmark(id.Value);

            if (bookmark == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);

            return View(bookmark);
        }

        [Authorize]
        public IActionResult Create()
        {
            AddAvailableCategoriesToViewData();
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookmarkModel bookmarkModel)
        {
            if (ModelState.IsValid)
            {
                var newBookmark = bookmarkModel.ToBookmark();
                
                if (!string.IsNullOrWhiteSpace(bookmarkModel.CategoryName))
                    newBookmark.Category = _categoryService.EnsureCategoryExists(
                        new Category()
                        { 
                            Name = bookmarkModel.CategoryName 
                        });
                
                _bookmarkService.CreateBookmark(newBookmark);

                return RedirectToAction("Index");
            }

            AddAvailableCategoriesToViewData();
            return View(bookmarkModel);
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);

            Bookmark bookmark = _bookmarkService.GetBookmark(id.Value);

            if (bookmark == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);

            AddAvailableCategoriesToViewData();
            var bookmarkModel = new BookmarkModel(bookmark);
            
            return View(bookmarkModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BookmarkModel bookmarkModel)
        {
            if (ModelState.IsValid)
            {
                var updateBookmark = bookmarkModel.ToBookmark();

                if (!string.IsNullOrWhiteSpace(bookmarkModel.CategoryName))
                    updateBookmark.Category = _categoryService.EnsureCategoryExists(
                        new Category() 
                        {
                            Name = bookmarkModel.CategoryName 
                        });
                
                _bookmarkService.UpdateBookmark(updateBookmark);
                
                return RedirectToAction("Index");
            }
            
            AddAvailableCategoriesToViewData();
            return View(bookmarkModel);
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            
            Bookmark bookmark = _bookmarkService.GetBookmark(id.Value);

            if (bookmark == null)
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);
            
            return View(bookmark);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Bookmark bookmark = _bookmarkService.GetBookmark(id);
            _bookmarkService.DeleteBookmark(bookmark);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public JsonResult SuggestCategories(string categoryNameStartsWith)
        {
            IEnumerable<string> matched = _categoryService
                .GetCategories()
                .Select(c => c.Name)
                .Where(c => c.ToLower().StartsWith(categoryNameStartsWith));

            return Json(matched);
        }

        private void AddAvailableCategoriesToViewData()
        {
            var availableCategoryNames = _categoryService.GetCategories().Select(c => c.Name);
            ViewData.Add("AvailableCategoryNames", availableCategoryNames);
        }

    }
}

ReadLater5/ReadLater5/Controllers/CategoriesController.cs
using Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReadLater5.Models;
using Services;
using System.Collections.Generic;

namespace ReadLater5.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IBookmarkService _bookmarkService;

        public CategoriesController(ICategoryService categoryService, IBookmarkService bookmarkService)
        {
            _categoryService = categoryService;
            _bookmarkService = bookmarkService;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<Category> model = _categoryService.GetCategories();
            return View(model);
        }

        [Authorize]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            Category category = _categoryService.GetCategory((int)id);
            if (category == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);
            }
            return View(category);

        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryModel categoryModel)
        {
            if (ModelState.IsValid)
            {
                _categoryService.EnsureCategoryExists(categoryModel.ToCategory());
                return RedirectToAction("Index");
            }

            return View(categoryModel);
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }
            Category category = _categoryService.GetCategory((int)id);
            if (category == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);
            }
            return View(category);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _categoryService.UpdateCategory(category);
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status400BadRequest);
            }

            Category category = _categoryService.GetCategory((int)id);
            
            if (category == null)
            {
                return new StatusCodeResult(Microsoft.AspNetCore.Http.StatusCodes.Status404NotFound);
            }

            var model = new CategoryDeleteModel()
            {
                Category = category,
                BookmarksToUncategorize = _bookmarkService.GetBookmarks(category.ID)
            };

            return View(model);
        }

        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Category category = _categoryService.GetCategory(id);
            _categoryService.DeleteCategory(category);
            return RedirectToAction("Index");
        }
    }
}

ReadLater5/ReadLater5/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReadLater5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReadLater5</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Bookmarks" asp-action="Index">Bookmarks</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ReadLater5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>